CREATE TABLE IF NOT EXISTS public.bot_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  telegram_id bigint,
  chat_id bigint,
  update_id bigint,
  event_type text NOT NULL,
  payload jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS bot_events_created_at_idx
  ON public.bot_events (created_at DESC);

CREATE INDEX IF NOT EXISTS bot_events_event_type_idx
  ON public.bot_events (event_type);

CREATE INDEX IF NOT EXISTS bot_events_telegram_id_idx
  ON public.bot_events (telegram_id);

CREATE TABLE IF NOT EXISTS public.bot_user_status (
  telegram_id bigint PRIMARY KEY,
  is_blocked boolean NOT NULL DEFAULT false,
  blocked_at timestamptz,
  unblocked_at timestamptz,
  last_error text,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS bot_user_status_is_blocked_idx
  ON public.bot_user_status (is_blocked);
